[general]
import = [
    "~/.config/alacritty/themes/monokai_pro_dark.toml"
]

[font]
normal = { family = "0xProtoNerdFontMono", style = "Regular" }

[window]
padding = { x = 2, y = 2 }
decorations = "None"

